---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGhuYWJ1dGYyCg==
  CLOUDINARY_KEY: ODI3MjEyOTY4NzY1NjQ3Cg==
  CLOUDINARY_SECRET: YWlVOE1TTGVCN2k3VGtPaDlsRi14VlhOeU93Cg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2libVZ6ZEdFM01TSXNJbUVpT2lKamJIZHdOWEp2YkdRd01XdHRNbkZ1YlhVMWN6SnBORGhsSW4wLnZlS0V3Y3ZMU2J5cV9GODY5Sk1vUXcK
  DB_URL: bW9uZ29kYitzcnY6Ly9uZXN0b3Jqb3N1ZWRpZ2JldTpBNnNtS1Ywb1NXQUZudXZHQGRldm9wc3N0YWNrLmRucDhrbmMubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPURldm9wc1N0YWNr
  SECRET: ZGV2b3BzbGFi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: nestafulto/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
